apiVersion: apps/v1
kind: Deployment
metadata:
  name: htbackend
  labels:
    app: HTBE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: HTBE
  template:
    metadata:
      labels:
        app: HTBE
    spec:
      containers:
      - name: htbackend
        env:
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_HOST_IP
          value: "0.0.0.0"
        - name: FLASK_HOST_PORT
          value: "5001"
        - name: Name
          value: "Irtiza"  
        image: aliartiza75/ht-be:0.0.5 # {"$imagepolicy": "<namespace>:<image-policy-name>"}
        ports:
        - containerPort: 5001
