---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ht-be
  annotations:
spec:
  ingressClassName: nginx-internal
  rules:
  - host: ht-be.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ht-be
            port: 
              number: 5001
