apiVersion: apps/v1
kind: Deployment
metadata:
  name: htbackendapi
  labels:
    app: BEAPI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BEAPI
  template:
    metadata:
      labels:
        app: BEAPI
    spec:
      containers:
      - name: backendapi
        env:
        - name: FLASK_ENV
          value: "development"
        - name: FLASK_HOST_IP
          value: "0.0.0.0"
        - name: FLASK_HOST_PORT
          value: "5001"
        - name: Name
          value: "Irtiza"  
        image: datetime_api:0.0.1
        ports:
        - containerPort: 5001
