apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: htbackend
  namespace: default
spec:
  interval: 10s
  path: ./deployments/kubernetes/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: htbackend
  validation: client